# Numpy

In [1]:
import numpy as np

- Create a 1D array of numbers from 0 to 9.


In [2]:
array_1D = np.arange(0, 10, 1)
array_1D

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- Write a NumPy program to Sum the elements for a given array.


In [3]:
array_1D = np.arange(0, 10, 1)

sum_array = np.sum(array_1D)
sum_array

np.int64(45)

- Write a NumPy program to get the average of the elements for a given array and for a given list.


In [4]:
l = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

array_1D = np.arange(0, 10, 1)

print(np.mean(array_1D))
print(array_1D.mean())

print(np.mean(l))


4.5
4.5
4.5


- Convert a 1D array of length 10 to a 2D array with 2 rows


In [5]:
array_1D = np.arange(0, 10, 1)

array_2D=array_1D.reshape(2, 5)
array_2D

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

- compute the square root for each element in the  array
 ([[1, 2, 3],[2, 3, 4],[4, 5, 6]])


In [6]:
array =np.array ([[1, 2, 3],
              [2, 3, 4],
              [4, 5, 6]])

square_root = np.sqrt(array)
square_root

array([[1.        , 1.41421356, 1.73205081],
       [1.41421356, 1.73205081, 2.        ],
       [2.        , 2.23606798, 2.44948974]])

- compute the exponential for each element in the above array


In [7]:
array =np.array ([[1, 2, 3],
              [2, 3, 4],
              [4, 5, 6]])

exponential = np.exp(array)
exponential 

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [  7.3890561 ,  20.08553692,  54.59815003],
       [ 54.59815003, 148.4131591 , 403.42879349]])

- sample 8 elements from uniform dist ([0, 1)


In [8]:
sample =np.random.uniform(0, 1, 8)
sample

array([0.06285243, 0.38635434, 0.61131076, 0.32685769, 0.56480856,
       0.67041019, 0.95235618, 0.59658166])

In [9]:
sample = np.random.rand(8)
sample

array([0.96302509, 0.06778926, 0.35790871, 0.40792249, 0.71891794,
       0.12673499, 0.36134138, 0.26157924])

- Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

In [10]:
vector = np.random.randint(0, 11, 5)
vector

array([10,  6,  6,  8,  3], dtype=int32)

- Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21

In [11]:
matrix = np.arange(10, 22).reshape(3, 4)
matrix

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

- Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.

In [12]:
vector = np.linspace(5, 50, 10)
vector

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

- Write a NumPy program to create an array of all the even integers from 30 to 70.

In [13]:
even_array = np.arange(30, 71, 2)
even_array

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

- Write a NumPy program to check whether two arrays are equal (element wise) or not

In [14]:
vector_1 = np.arange(0, 10, 1)

vector_2 = np.arange(2, 12, 1)

vector_1 == vector_2

array([False, False, False, False, False, False, False, False, False,
       False])